2020-11-22 08:32:47,737 ERROR: Exception on /video/1 [GET] [in /home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zodindev/projects/Malphas/app/media/routes.py", line 52, in video
    return render_template('media/video.html', title=video.title, video=video, comments=comments.items, form=form, next_url=next_url, prev_url=prev_url, all_vids=all_vids)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/zodindev/projects/Malphas/app/templates/media/video.html", line 15, in template
    {% wtf.quick_form(form) %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'wtf'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-11-22 08:34:23,818 INFO: Malphas-Web startup [in /home/zodindev/projects/Malphas/app/__init__.py:96]
2020-11-22 08:35:00,099 ERROR: Exception on /video/1 [POST] [in /home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zodindev/projects/Malphas/app/media/routes.py", line 39, in video
    comment = Comment(body=form.comment.data, video=video, author=current_user)
AttributeError: 'CommentForm' object has no attribute 'comment'
2020-11-22 08:35:20,685 INFO: Malphas-Web startup [in /home/zodindev/projects/Malphas/app/__init__.py:96]
2020-11-22 08:35:34,400 ERROR: Exception on /video/1 [GET] [in /home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zodindev/projects/Malphas/app/media/routes.py", line 52, in video
    return render_template('media/video.html', title=video.title, video=video, comments=comments.items, form=form, next_url=next_url, prev_url=prev_url, all_vids=all_vids)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/zodindev/projects/Malphas/app/templates/media/video.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/zodindev/projects/Malphas/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/zodindev/projects/Malphas/app/templates/base.html", line 94, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/zodindev/projects/Malphas/app/templates/media/video.html", line 18, in block "app_content"
    {% include '_comment.html' %}
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _comment.html
2020-11-22 08:36:16,744 INFO: Malphas-Web startup [in /home/zodindev/projects/Malphas/app/__init__.py:96]
2020-11-22 08:37:33,063 ERROR: Exception on /upload_photo [POST] [in /home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zodindev/projects/Malphas/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/zodindev/projects/Malphas/app/media/routes.py", line 101, in upload_photo
    if not allowed_image_file(f.filename):
NameError: name 'allowed_image_file' is not defined
2020-11-22 08:38:12,006 INFO: Malphas-Web startup [in /home/zodindev/projects/Malphas/app/__init__.py:96]
